Metrics/AbcSize:
  Max: 21

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 17

Metrics/ModuleLength:
  Max: 102

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/DoubleNegation:
  Enabled: false

Style/PredicateName:
  Enabled: false
